### ISSUE TITLE
No state update for lights

### ISSUE THREAD

**Issue by HaSHi93110** [iMicknl/ha-tahoma#229]
hi.
I have test your integration. 
I have in my tahoma box a legrand light which is linked from legrand account.
In the tahoma application the state of my light works good. When i turn on the light in my legrand application, the state in the tahoma application refresh and show me on. But in ha, i can't see the state on of my light. The state is always off and i can't change manually the state.

**Comment by iMicknl** [comment]
@HaSHi93110 thanks for your report. Could you please follow the bug report template? This template consist of multiple questions and details. In order to help you, we would need to understand what kind of device you are using and the version.

I will close this one, but feel free to open a new one using the template.
