### ISSUE TITLE
Newly added devices require a restart of home assistant

### ISSUE THREAD

**Issue by golles** [iMicknl/ha-tahoma#279]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
Today my 2 new roller shutters (IO) were installed and I've added them in the Somfy app. I had to restart HA to make them appear there. I would expect that a restart would not be needed (in the final version of this component)

**To Reproduce**
Add new devices to Somfy app/website (https://www.tahomalink.com/)
Devices not appearing in HA
following logs are appearing:
`2020-09-29 18:37:00 DEBUG (MainThread) [custom_components.tahoma] Finished fetching TaHoma Event Fetcher data in 0.108 seconds`
Devices not appearing in HA after waiting for 10-15 minutes
Reboot HA
Devices are there :-)

**Expected behavior**
Newly added devices get added to HA without restarting

**Screenshots**
None

**Environment (please complete the following information):**

- **ha-tahoma version:** master, commit: 7c1f11d2158dfeec74ebd6434fdade89128041b5 (latest available as of creating this ticket)
- **Home Assistant version:** 0.115.5, also latest
- **Platform**: cover

**Device:**
Roller shutter

- **Model**: PositionableRollerShutter
- **Type**: io:RollerShutterGenericIOComponent

**Additional context**
I guess the component is not mature enough to support this, maybe it's not a bug but a feature request. 
Again I want to express that you're all doing an amazing job making this new component, I'm very happy with it!

**Comment by iMicknl** [comment]
Thanks for reporting @golles! This is something that we haven't implemented (yet) indeed. We already catch the `DeviceCreatedEvent`, however we don't reload the integration at the moment.

This is something that has a bit of a lower prio than the other open issues, since you can currently 'reload' the integration via the UI, which will add them as well. A full restart is not needed anymore since 0.115.

https://github.com/iMicknl/ha-tahoma/blob/7c1f11d2158dfeec74ebd6434fdade89128041b5/custom_components/tahoma/coordinator.py#L79-L83

**Comment by golles** [comment]
I'm not planning to buy any new devices soon, so won't be able to test any time soon :-)

**Comment by toby200** [comment]
@iMicknl I've just got a new roller-garage door, with a connexoon hub and rollixo rts controller. If there's anything I could do before I try adding this to home assistant that would help in terms of gathering logs or whatever please let me know and I'd be happy to help as much as I can.

**Comment by iMicknl** [comment]
@toby200 thanks! is your Connexoon already setup and would you be adding the new device to Connexoon? 
I could create a new integration version with extra logging, so that we can catch more information.

**Comment by toby200** [comment]
Ah I'm sorry I think I've maybe misunderstood the situation.... I've already got the device added to Connexoon, and just need to add the whole system to home assistant. At the moment I've not even added the integration. So I think that's a slightly different scenario to the issue here.

If you'd like any extra logging anyway let me know and I'd be happy to help but if it's not relevant to this then I'll just proceed as normal.

**Comment by iMicknl** [comment]
@toby200 no worries, in that case everything should work out of the box. 👍🏻. You can just proceed as normal.

**Comment by toby200** [comment]
Ok thanks, sorry for the confusion

**Comment by iMicknl** [comment]
We should have a look at this code, https://github.com/home-assistant/core/blob/dev/homeassistant/components/uptimerobot/__init__.py#L93-L113. This is how uptime robot handles this scenario.
