### ISSUE TITLE
Partial Zone A, B C (alarm somfy gamme ASR)

### ISSUE THREAD

**Issue by Carmickael-19** [iMicknl/ha-tahoma#331]
Hello
I had a quick question about using the alarm control.
I manage to desactivate and activate it in total mode with "alarm_control_panel.alarm_arm_away" et "alarm_control_panel.alarm_disarm", but unable to activate partial or zone mode A, B or C.
Is there a particular action to perform? or is it not compatible with my RTS alarm?
Thank you, for your help. 

for information my somfy alarm is of type: GAMME ASR

**Comment by iMicknl** [comment]
Thanks for reporting, @Carmickael-19. We need more information in order to understand your issue and device.

Could you please create [a new issue](https://github.com/iMicknl/ha-tahoma/issues/new?assignees=&labels=bug&template=bug_report.md&title=) using the provided issue template? Especially the model of your device is important.

**Comment by iMicknl** [comment]
@Carmickael-19 do you still encounter this issue?
