### ISSUE TITLE
Cozytouch : Toweldryer

### ISSUE THREAD

**Issue by BluntVanille** [iMicknl/ha-tahoma#397]
Hello here ! 

I got a Symphonik towel dryer from Thermor. Everything look's ok from the integration but i cannot control anything. Is there a way to got thermostat here ? 
![image](https://user-images.githubusercontent.com/77114369/109861978-34d4d480-7c60-11eb-80ce-93e302e8136a.png)

![image](https://user-images.githubusercontent.com/77114369/109862025-40c09680-7c60-11eb-8584-e38d1f79f0fc.png)

Tell me how can I help ! 

Thank you !

**Comment by iMicknl** [comment]
@BluntVanille thanks for reporting. Could you perhaps have a look at the README (and the issue template)? We need more information in order to investigate your device.

Please create a [new issue](https://github.com/iMicknl/ha-tahoma/issues/new?assignees=&labels=new-device&template=unsupported-device.md&title=Add+support+for+ModelName+%28io%3ASomfySensorName%29) with the 'Unsupported device' template and fill in all details.

Don't forget to turn on debug logging. https://github.com/iMicknl/ha-tahoma#enable-debug-logging. I will close this issue for now, but feel free to create a new one with all the details.
