### ISSUE TITLE
Tahoma Switch Box Connection Problems

### ISSUE THREAD

**Issue by chavalaloco** [iMicknl/ha-tahoma#507]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

I‘ve set up the tahoma switch box with my motor and it works just fine with the app. But I can’t get the homeassistant intergration to work. it always shows a error message that my credentials are wrong. I also can’t login at the tahomlink page, but on the somfy page it works fine. 

Does anyone has such problems with the somfy switch box?

### What version of this integration (ha-tahoma) has the issue?

2.5.2

### What version of Home Assistant Core has the issue?

Core-2021.8.1

### Which gateway / hub do you use?

Somfy tahoma switch

### Device model

—

### Device type

—

**Comment by iMicknl** [comment]
Thanks for reporting, @chavalaloco! Do you live in Europe? 

Have you tried selecting 'Somfy TaHoma' as your hub? This should work for the TaHoma switch with the same credentials as what you use for the iOS / Android app.

**Comment by chavalaloco** [comment]
Yes i did. already before. I found the problem. 
I didn't Setup a scene in the tahoma app. After doing that it works now. 

Thanks for your help!

**Comment by chavalaloco** [comment]
FYI: the tahomalink login still doesn't work.

**Comment by iMicknl** [comment]
> I didn't Setup a scene in the tahoma app. After doing that it works now.

I am not sure if I understand correctly. But you had to first create a scene in the TaHoma app, and afterwards you could use the login? Maybe we should document this in our README.

**Comment by chavalaloco** [comment]
That's correct.

**Comment by antoineguilbert** [comment]
I have the same problem. I can't use my Tahoma Switch on Home Assistant. I used before the Tahoma V2. What kind of scenes did you create @chavalaloco ?

**Comment by chavalaloco** [comment]
I created just a manual scene which closes the cover.

![image](https://user-images.githubusercontent.com/59644594/128612144-86f291bc-d641-4128-ab24-88a89e07acbf.jpeg)

**Comment by antoineguilbert** [comment]
I've already this kind of scene. 
What do you choose here ? Tahoma not working for me (because tahomalink not working with Tahoma Switch)

 
<img width="388" alt="Capture d’écran 2021-08-07 à 21 44 07" src="https://user-images.githubusercontent.com/16510381/128612212-799ef768-662b-4eaf-9d9c-aa81924e7ee1.png">

**Comment by chavalaloco** [comment]
> I've already this kind of scene. 
> 
> What do you choose here ? Tahoma not working for me (because tahomalink not working with Tahoma Switch)
> 
> 
> 
>  
> 
> <img width="388" alt="Capture d’écran 2021-08-07 à 21 44 07" src="https://user-images.githubusercontent.com/16510381/128612212-799ef768-662b-4eaf-9d9c-aa81924e7ee1.png">
> 
> 

I chooses Somfy Tahoma. It doesn't matter if you can login to tahomalink or not, I can't anyway but home assistant could login and show my somfy devices. What I also did is plugging the switch off and leave it like that for a couple of hours (I think i left it for 3 or 4 hours), then I created this scene and i could successfully login.

**Comment by Egobo2001** [comment]
Hello.
I have a Tahoma V2 box with a Zwave key 868.42Mhz on it.
When i integated my Tahoma in HA , all products apear and sems to be controled execpt Zwave products.
Indeed, when i command the Zwave product, the slider dgoes on the oposit position and come back on first position without command the product (and stay on gray position). Also , on Tahoma , the same Zwave products are not anymore usable . When i push the physical swith to switch on the product , the information come up to Tahoma and HA.
I removed the "Overkiz (by Somfy) - Custom component" and my Tahoma operate normally again with Zwave products.
Have you got a solution for it ?
And i clarify that i don't want plug my zwave key on HA and transfert all Zwave product on HA ,even if i know it's possible, because all familly use Tahoma and HA is not ready for me and need more of time to treansfert the "users" to it...
Thank you in advence.
