### ISSUE TITLE
Add support for RAK-50RXB / SPX-WFG02 / AirCloud Home

### ISSUE THREAD

**Issue by EmmanuelVella** [iMicknl/ha-tahoma#527]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

Hello,

I have an Hitachi RAK-50RXB and just added a SPX-WFG02 wifi module to control it via the AirCloud Home app. When I install the integration, I tried to use the Hi Kumo / Somfy servers without success (invalid credentials).

Would it be possible to support these server / devices ? 

Thank you !

https://aircloudhome.hitachiaircon.com/en

### Which gateway / hub do you use?

AirCloud Home

### Device model (optional)

SPX-WFG02

**Comment by iMicknl** [comment]
@EmmanuelVella thanks for reporting! Unfortunately, it seems that AirCloud Home is a hub/platform that is not using the Overkiz platform. This means that we cannot support it from this integration. 

I decompiled the Android app and it seems that their API is located at https://api-global-prod.aircloudhome.com. However, in order to write an integration, you would need to do quite some reverse engineering if they don't have public API documentation.

**Comment by EmmanuelVella** [comment]
Thank you for you fast answer ! That's sad, I just sent them an email to know if they propose a public API. I will let you know ! 👍
