### ISSUE TITLE
The (entity registry) area is reset on every reboot to All House

### ISSUE THREAD

**Issue by majorhector** [iMicknl/ha-tahoma#566]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Everytime I restart my server this integration set automattically to "All House" the area of my connected devices.

![Cattura](https://user-images.githubusercontent.com/81853764/133489846-e3ed83d6-840b-4bbd-9b4b-b3473d1a62de.PNG)

I delete the area or set the devices to a new room but when I restart the server "All House" pop-up again

### What version of this integration (ha-tahoma) has the issue?

2.7.2

### What version of Home Assistant Core has the issue?

core-2021.9.4

### Which gateway / hub do you use?

Somfy Connexoon

### Device model

![GitHub Logo](/images/logo.png) Format: ![Alt Text](url)

### Device type

Firmware: 5100394X23?

### Additional information

I have no error in the log

**Comment by tetienne** [comment]
Hi, I was indeed able to reproduce with our integration and with Hue but only when I delete the area from the device. When updating the area by another one, this one is not overrided after a reboot.

Can you check with another integration if you have the same issue? It seems related to HA core.

**Comment by majorhector** [comment]
I have updated an area with another one and it remain. I have tested with another integration and I have no problem at all to remove the area.

I have also noticed that Connexoon hub (model "Thaoma Premium") is listed with no area set

**Comment by iMicknl** [comment]
@majorhector I just tried it on my instance with the latest ha-tahoma integration and latest core version, and I am unfortunately not able to reproduce your issue.

I have the same results as @tetienne. When I remove an area, it will be reset to the area that we retrieve from the Overkiz API. When I manually change the 'Overkiz assigned' area to a custom created area, it will be persisted after a reboot.

**Comment by iMicknl** [comment]
Unfortunately, this is a 'bug' (or feature 😉) in Home Assistant core. As @tetienne mentioned, the same behavior happens with the Hue integration. Home Assistant allows integrations to sync the device areas to Home Assistant upon every boot. Apparently when someone removes an area, on the next boot it will sync it again, which is not the behavior you are looking for.

> This is the only integration that can't me let remove an area. In the connexoon app I can't set an area. So why "all house" pop up at every restart? And where came from?

Area support is part of the Overkiz platform, where Somfy Connexoon is built upon. However, it seems that the Connexoon platform doesn't have an option to change those and they will just return 'All House' for every device.

This should be fixed in core and not in our integration I believe. The only fix we can do is to not sync area's when they all have 'All House' as the name, however that will be different in every language.

**Comment by majorhector** [comment]
Ok. Thank for the explanation 🙂 I've tought was a big of this integration
