### ISSUE TITLE
Add ‚optimistic‘ mode for rts-devices

### ISSUE THREAD

**Issue by kwithus** [iMicknl/ha-tahoma#694]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The request

Would be nice if this addon integrates the ‚optimistic‘ mode which is provided by the Somy Integration. With this mode enabled the Somfy integrations (tries to) track the state of rts-devices, which don’t send their state on themselves.

### Which gateway / hub do you use?

Somfy Tahoma 

### Device type (optional)

Rts covers

**Comment by sh4rks** [comment]
+1
It will be useful for some integrations because we haven’t any state with rts devices

**Comment by iMicknl** [comment]
We won't support this, since this shouldn't be part of our integration and I don't think this is allowed anymore for core integrations. 

In my opinion, an integration should reflect the device 1:1 and thus not add an optimistic mode. We add `assumed_state` (https://www.home-assistant.io/docs/configuration/customizing-devices/#assumed_state) for RTS devices and there should be other integrations that can build an optimistic cover (or cover template) based on this cover.
