### ISSUE TITLE
HACS Installation

### ISSUE THREAD

**Issue by ColinRobbins** [iMicknl/ha-tahoma#702]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

When I installed via HACS, the software was loaded into
```
custom_components/tahoma/tahoma
```
where HA did not find it.
I had to manually move the files up one level to
```
custom_components/tahoma
```

(From here it worked perfectly - I've migrated from the Somfy integration.  Thank you for you hard work)

### What version of this integration (ha-tahoma) has the issue?

2.10.2

### What version of Home Assistant Core has the issue?

2021.12.8

### Which gateway / hub do you use?

Connexoon Rts

### Device model

Connexoon Rts

### Home Assistant log

```shell
N/A
```

### Additional information

HACS Version: 1.19.0

**Comment by iMicknl** [comment]
Thanks for reporting! Unfortunately I can not reproduce this issue and we haven't heard this before. Let's see if other people report the same in the coming days.

We hope to have added most of the functionality of this integration in core in 2022.3 or 4, so that the custom component isn't required anymore.
