### ISSUE TITLE
 A new release of pip available: 22.2.1 -> 22.3 

### ISSUE THREAD

**Issue by uowis** [iMicknl/ha-tahoma#824]
### The problem

Hello, 
After update to Operating System 9.3 i have this error : 

### What version of this integration (ha-tahoma) has the issue?

2022.11.0

### What version of Home Assistant Core has the issue?

Operating System 9.3

### Which gateway / hub do you use?

Cozytouch

### Home Assistant log

```
Unable to install package pyoverkiz==1.3.6: ERROR: Cannot install pyoverkiz==1.3.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.2.1 -> 22.3 [notice] To update, run: pip install --upgrade pip```

**Comment by iMicknl** [comment]
Was it after 2022.11 or after 9.3? 

Is there a reason why you could not upgrade to our core component yet? :)

**Comment by Mushu77** [comment]
Hello @iMicknl ,
I can't speak for @uowis , but in my case I can't upgrade to core component because I have Somfy shutter and Atlantic Heater and unfortunately "AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint" is not backported yet :-(

**Comment by tillstaff** [comment]
Hello @iMicknl 

I have the same problem with the last 2022.11 update and I can't move to the core component for now because I miss one last climate device (atlantic_electrical_heater_with_adjustable_temperature_setpoint).

To correct this problem, a bump to the last "pyoverkiz" 1.5.6 seems to work fine.
https://github.com/iMicknl/ha-tahoma/blob/69f9a2d91f4d6538364ae541628b3879709e9b7f/custom_components/tahoma/manifest.json#L7-L9

But I still have the following notification :
![image](https://user-images.githubusercontent.com/11087736/199730891-e5bb50bc-cc36-4b77-a8b4-acaa24ca7753.png)

**Comment by Hankey71** [comment]
@iMicknl @Mushu77 @tillstaff 
Same problem for me !

In my logs:
`Logger: homeassistant.setup
Source: setup.py:184
First occurred: 15:16:53 (1 occurrences)
Last logged: 15:16:53

Setup failed for custom integration tahoma: Requirements for tahoma not found: ['pyoverkiz==1.3.6'].`

and

`Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 15:16:39 (3 occurrences)
Last logged: 15:16:53

Unable to install package pyoverkiz==1.3.6: ERROR: Cannot install pyoverkiz==1.3.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.2.1 -> 22.3 [notice] To update, run: pip install --upgrade pip`

since HA 2022.11.0 update with Supervisor 2022.10.0 and Operating System 9.3.
Overkiz (by Somfy) - Custom component v2.13.0
I need custom component for my climate device (atlantic_electrical_heater_with_adjustable_temperature_setpoint).

How can I help you ? I have already give you my id for test, so if you want tell me !

**Comment by ghostsam45** [comment]
Hello,

Same problem for me !

**Comment by eichenlauba** [comment]
Hi!
Same problem here since 2022.11 update..

**Comment by uowis** [comment]
Hello @iMicknl  ! 
I need (only) AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint

**Comment by iMicknl** [comment]
Could you give https://github.com/iMicknl/ha-tahoma/archive/refs/heads/fix/ha_2022.11.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

This should fix it for now, but I have not been able to test it. Would be great if someone could test this before we merge it.

**Comment by Mushu77** [comment]
Hello @iMicknl,
this fix work for me :-)
Thank You

**Comment by Hankey71** [comment]
Yes ! It's OK for me too on HA 2022.11.1, Supervisor 2022.10.2 and Operating System 9.3.
Thank you very much @iMicknl !
My 'io:AtlanticElectricalHeaterWithAdjustableTemperatureSetpointIOComponent' : Thermor Equateur 4

**Comment by Hankey71** [comment]
But I still have these issues:

> Logger: homeassistant.components.number
> Source: components/number/__init__.py:117
> Integration: Nombre (documentation, issues)
> First occurred: 00:08:46 (5 occurrences)
> Last logged: 00:08:46
> 
> custom_components.tahoma.number is setting deprecated attributes on an instance of NumberEntityDescription, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
> custom_components.tahoma.number::OverkizNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

> Logger: homeassistant.components.number
> Source: components/number/__init__.py:249
> Integration: Nombre (documentation, issues)
> First occurred: 00:08:46 (10 occurrences)
> Last logged: 00:08:46
> 
> Entity None (<class 'custom_components.tahoma.number.OverkizNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom integration author.

and:

> Logger: homeassistant.helpers.frame
> Source: helpers/frame.py:77
> First occurred: 00:08:46 (2 occurrences)
> Last logged: 00:08:46
> 
> Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom integration author for tahoma using this method at custom_components/tahoma/__init__.py, line 141: device_registry = await dr.async_get_registry(hass)
> Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom integration author for tahoma using this method at custom_components/tahoma/climate_devices/atlantic_electrical_heater_with_adjustable_temperature_setpoint.py, line 109: entity_registry = await self.hass.helpers.entity_registry.async_get_registry()

**Comment by ghostsam45** [comment]
Hello @iMicknl,

My 'io:AtlanticElectricalHeaterWithAdjustableTemperatureSetpointIOComponent' : Atlantic Divali

**Comment by standu2186** [comment]
iMicknl,
Solved for me with the provided package.
Thanks

**Comment by iMicknl** [comment]
@Hankey71 can you try with the latest version? Just download the zip again. Let me know if it still works and if it fixes the warnings above.

**Comment by ckd77** [comment]
@iMicknl thanks. The zip was able to make my heating functional again :)

**Comment by Hankey71** [comment]
> @Hankey71 can you try with the latest version? Just download the zip again. Let me know if it still works and if it fixes the warnings above.

Thank you @iMicknl ! With the latest version, it's OK ! I no longer have any error messages in my logs.
You are at the top and thank you again for the speed of your answers!

**Comment by iMicknl** [comment]
You can now update via HACS or releases and it should be fixed.

**Comment by uowis** [comment]
It work fine Thanks !

**Comment by eichenlauba** [comment]
Hi! The update via HACS work fine. Until my automations change the preset mode of my heaters.. Every change in preset mode break there status, controls and informations.
Before preset change : 
![image](https://user-images.githubusercontent.com/6337122/200433153-972830ba-cb28-42d4-bda0-fff87990d714.png)

After change : 
![image](https://user-images.githubusercontent.com/6337122/200434568-9bb536ce-0352-46e1-9c04-3218dc1a812d.png)

If i reload the integration, it's working again but not every time..

Anyone as the same problem?
