### ISSUE TITLE
Problem afer update top "Home Assistant 2023.5.2"

### ISSUE THREAD

**Issue by kindlma** [iMicknl/ha-tahoma#845]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Logger: homeassistant.setup
Source: setup.py:252
First occurred: 12:36:49 (1 occurrences)
Last logged: 12:36:49

Setup failed for custom integration tahoma: No setup or config entry setup function defined.

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

### What version of this integration (ha-tahoma) has the issue?

V2.15.0

### What version of Home Assistant Core has the issue?

10.1

### Which gateway / hub do you use?

Overkiz

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by chabou-san** [comment]
This is due to a deprecation notice of the "config entry setup" previously reported in the logs, that ended up removed in this month's release.
Integrations need to do things differently, but as this integration is not supported anymore (see deprecation notice in README.md), it is very unlikely to see this bug fixed. You are advised to use the official integration available in Core Home Assistant.

But if you are like me (stuck with this integration due to _Hi Kumo Hub_ not yet supported in Core), I don't see another way than downgrading your version of Home Assistant.

**Comment by iMicknl** [comment]
Update to [v2.15.0](https://github.com/iMicknl/ha-tahoma/releases/tag/v2.15.0).

@kindlma which devices are not supported yet on core for you?

@chabou-san which device is not supported for you in core? Hi Kumo Hub is supported for sure, but not all devices are migrated yet.

**Comment by chabou-san** [comment]
Oh great, I missed that update ! Many many thanks. :) 

I'm using AirToAir Heat Pump climate entities from Hi Kumo (and I'm frequently, yet patiently, checking the status of that PR https://github.com/home-assistant/core/pull/81743). ;) 
Keep up the good work guys !
